### PR TITLE
Milestone 4: Portfolio

### PR DESCRIPTION
**Pull request by davmba**
### Desktop version milestone 4: Portfolio

**In this milestone we:**

- Used media queries to make sure that the website displays correctly on desktop screens.

### CODE REVIEW

**Comment by davmba** [comment]
### Desktop Version
The desktop display was added to the portfolio, and was made responsive with the help of media quaries

**Review by topeogunleye — COMMENTED** [review]
Hi @davmba, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️

   - You have submitted a project, that doesn't have a pull request description, kindly add one in the appropriate place and not as a comment. See a demo on how to add a PR description below:


>- [ ] Please kindly add a more descriptive PR title.
> See a demo below:
pull_request_desc
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

>Invalid Code Review Request **does not count** into the code reviews limit.

**Comment by davmba** [comment]
### Desktop version milestone 4: Portfolio

In this milestone: 

- Use media queries to make sure that your website displays correctly on desktop screens.

**Comment by topeogunleye** [comment]
> ### Desktop version milestone 4: Portfolio
> In this milestone:
> 
> * Use media queries to make sure that your website displays correctly on desktop screens.

@davmba, this is not how to add a PR description please. I kindly suggest that you add it at the top here:

image

**Comment by topeogunleye** [comment]
> > ### Desktop version milestone 4: Portfolio
> > In this milestone:
> > 
> > * Use media queries to make sure that your website displays correctly on desktop screens.
> 
> @davmba, this is not how to add a PR description please. I kindly suggest that you add it at the top here:
> 
> image

Great Job adding a PR Description :+1:

**Pull request merged**
